// Hardcoded credentials - App Supabase
export const APP_SUPABASE_URL = 'https://amjrbybrlphsvvfqusqh.supabase.co';
export const APP_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtamJ5YnJscGhzdnZmcXVzcWgiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc3NTQ3NDQ1MCwiZXhwIjoyMDkxMDUwNDUwfQ.Q2AhhvPQskgSqLnuMBX0qNXncPYSedDBirfo_Sap0gQ';

// Hardcoded credentials - Finance Bot Supabase
export const FINANCE_SUPABASE_URL = 'https://qlipgighvdzxsllzghgl.supabase.co';
export const FINANCE_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsaXBnaWdodmR6eHNsbHpnaGdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDg0NzksImV4cCI6MjA2NTMyNDQ3OX0.vwRkW6XX7-VBeLhYqRcUNl15oLqMpW0lZtZa9x_YSkA';
